version: 2.1
jobs:
  minicap-shared:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large
    steps:
      - run:
          name: LFS Install
          command: |
            sudo apt install -y git-lfs
            git lfs install
      - checkout
      - run:
          name: "Build"
          command: |
            cd jni/minicap-shared/aosp
            make

workflows:
  say-hello-workflow:
    jobs:
      - minicap-shared
